# Uncomment the next line to define a global platform for your project
 platform :ios, '7.0'

target 'RWTFlickrSearch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RWTFlickrSearch
  pod 'ReactiveCocoa'
pod 'objectiveflickr'
pod 'LinqToObjectiveC'
pod 'SDWebImage'
  target 'RWTFlickrSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
