# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Swift_EX_1' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_EX_1
	pod 'AFNetworking'
	pod 'MJExtension'
	pod 'SDWebImage'
	pod 'FMDB'
end
