# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Socket_Client' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CocoaAsyncSocket'
  # Pods for Socket_Client

end
